config/routes.rb
Rails.application.routes.draw do
  get 'users2/new'

  get 'sessions/new'

  resources :quotes
  get 'welcome/index'

  resources :quotes

  resources :users

  resources :judges

  resources :ideologies

  get '/faq' => 'faq#faq'
  get '/play' => 'ideologies#new'
  get '/signup' => 'users#new'
  get '/judge' => 'judges#new'
  get '/leaderboard' => 'users#leaderboard'
  get '/my_profile' => 'user_profile#index'
  get '/login'   => 'sessions#new'
  post '/login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  root 'welcome#index'

end

app/models/judge.rb
class Judge < ActiveRecord::Base

  validates_presence_of :ideology
  validates_presence_of :sentiment
  validates_presence_of :user

end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  before_action :set_judge, only: [:show, :edit, :update, :destroy]

  def index
    @judges = Judge.all
  end

  def show
  end

  def new
    # feed a random item from ideologies table to the form
    @ideology = Ideology.offset(rand(Ideology.count)).first
    @judge = Judge.new
  end

  def edit
  end

  def create
    @judge = Judge.new(judge_params)

    respond_to do |format|
      if @judge.save
        format.html { redirect_to @judge, notice: 'Sentiment was successfully created.' }
        format.json { render :show, status: :created, location: @judge }
      else
        format.html { render :new }
        format.json { render json: @judge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @judge.update(judge_params)
        format.html { redirect_to @judge, notice: 'Sentiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @judge }
      else
        format.html { render :edit }
        format.json { render json: @judge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @judge.destroy
    respond_to do |format|
      format.html { redirect_to @judges_url, notice: 'Sentiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_judge
    @judge = Judge.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def judge_params
    params.require(:judge).permit(:ideology, :sentiment, :user)
  end
end

app/helpers/judge_helper.rb
module JudgeHelper
end

app/views/judges/_form.html.erb
<%= form_for(@judge) do |f| %>
  <% if @judge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@judge.errors.count, "error") %> prohibited this sentiment from being saved:</h2>

      <ul>
      <% @judge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="modal-body">
      <form role="form">
    <div class="form-group">
      <%= f.label :Ideology %><br>
      <% if @ideology.blank? %>
          <%= f.text_area :ideology, class: 'form-control'%>
      <% else %>
          <%= f.text_area :ideology, class: 'form-control', :value => ideology.quote %>
      <% end %>
    </div>
        <div class="form-group">
          <%= f.label :Sentiment, class: 'text-center' %>
          </br>
          <%= f.text_field :sentiment, class: 'form-control' %>
        </div>

        <%= f.hidden_field :user, :value => session[:user_id] %>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-block btn-default btn-success'%>
  </div>

        </form>
      </div>
<% end %>

app/views/judges/edit.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
<h1 class="margin-base-vertical text-center">Editing Sentiment</h1>
</div>
<%= render 'form' %>

    <p class='text-center'>
<%= link_to 'ShowAll', judges_path, class: 'btn btn-default btn-xs' %>
</p>
  </div>
  </div>

app/views/judges/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default">
      <p id="notice"><%= notice %></p>

      <h1 class="margin-base-vertical text-center">Listing All Present Ideologies</h1>

      <table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Ideology</th>
      <th>Sentiment</th>
      <th>Rated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <% @judges.each do |judge| %>
            <tr>
              <td><%= judge.ideology %></td>
              <td><%= judge.sentiment %></td>
              <td><%= judge.user %></td>
              <td><%= link_to 'Edit', edit_judge_path(judge) %></td>
            </tr>
        <% end %>
  </tbody>
</table>

<br>
</div>
    </div>
  </div>

app/views/judges/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default">
      <p id="notice"><%= notice %></p>

      <h1 class="margin-base-vertical text-center">Random Ideology</h1>

      <table class="table table-striped table-condensed table-hover">

        <thead>
        <tr>
          <th>Name</th>
          <th>Association Level</th>
          <th>Sample Quote</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <td><%= @ideology.name %></td>
        <td><%= @ideology.association_level %></td>
        <td><%= @ideology.quote %></td>
        </tbody>
      </table>


<%= render 'form', :ideology => @ideology %>

      </div>
    </div>
</div>

app/views/judges/show.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
<h2 class="margin-base-vertical text-center" id="notice"><%= notice %></h2>
</div>
<p class='text-center'>
  <strong >Ideology:</strong>
  <%= @judge.ideology %>
</p>

<p class='text-center'>
  <strong>Sentiment:</strong>
  <%= @judge.sentiment %>
</p>

    <p class='text-center'>
<%= link_to 'ShowAll', judges_path, class: 'btn btn-default btn-xs' %>
    </p>
</div>
  </div>