config/routes.rb
Rails.application.routes.draw do
  get 'users2/new'

  get 'sessions/new'

  resources :quotes
  get 'welcome/index'

  resources :quotes

  resources :users

  resources :judges

  resources :ideologies

  get '/faq' => 'faq#faq'
  get '/play' => 'ideologies#new'
  get '/signup' => 'users#new'
  get '/judge' => 'judges#new'
  get '/leaderboard' => 'users#leaderboard'
  get '/my_profile' => 'user_profile#index'
  get '/login'   => 'sessions#new'
  post '/login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  root 'welcome#index'

end

app/models/ideology.rb
class Ideology < ActiveRecord::Base

  validates_presence_of :name
  validates_presence_of :quote
  validates_presence_of :association_level
  validates_presence_of :rated_by

end

app/controllers/ideologies_controller.rb
class IdeologiesController < ApplicationController
  before_action :set_ideology, only: [:show, :edit, :update, :destroy]

  # GET /ideologies
  # GET /ideologies.json
  def index
    @ideologies = Ideology.all
  end

  # GET /ideologies/1
  # GET /ideologies/1.json
  def show
  end

  # GET /ideologies/new
  def new
    # pick a quote at random and feed it to the form
    @quote = Quote.offset(rand(Quote.count)).first
    @ideology = Ideology.new
  end

  # GET /ideologies/1/edit
  def edit
  end

  # POST /ideologies
  # POST /ideologies.json
  def create
    @ideology = Ideology.new(ideology_params)

    respond_to do |format|
      if @ideology.save
        format.html { redirect_to @ideology, notice: 'Ideology was successfully created.' }
        format.json { render :show, status: :created, location: @ideology }
      else
        format.html { render :new }
        format.json { render json: @ideology.errors, status: :unprocessable_entity }
      end
    end

    sql = "Update users set score=score+10 where id='#{session[:user_id]}'"
    ActiveRecord::Base.connection.execute(sql)
  end

  # PATCH/PUT /ideologies/1
  # PATCH/PUT /ideologies/1.json
  def update
    respond_to do |format|
      if @ideology.update(ideology_params)
        format.html { redirect_to @ideology, notice: 'Ideology was successfully updated.' }
        format.json { render :show, status: :ok, location: @ideology }
      else
        format.html { render :edit }
        format.json { render json: @ideology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideologies/1
  # DELETE /ideologies/1.json
  def destroy
    @ideology.destroy
    respond_to do |format|
      format.html { redirect_to ideologies_url, notice: 'Ideology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ideology
    @ideology = Ideology.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ideology_params
    params.require(:ideology).permit(:name, :association_level, :quote, :rated_by)
  end
end

app/helpers/ideologies_helper.rb
module IdeologiesHelper
end

app/views/ideologies/_form.html.erb
<%= form_for(@ideology) do |f| %>
  <% if @ideology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ideology.errors.count, "error") %> prohibited this ideology from being saved:</h2>

      <ul>
      <% @ideology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="modal-body">
      <form role="form">
  <div class="form-group">
    <%= f.label :name, class: 'text-center' %>
    </br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
    <div class="form-group">
      <%= f.label :quote %><br>
      <% if @quote.blank? %>
          <%= f.text_area :quote, class: 'form-control'%>
      <% else %>
          <%= f.text_area :quote, class: 'form-control', :value => quote.content %>
      <% end %>
    </div>

  <div class="form-group">
    <%= f.label :association %><br>
    <%= f.text_field :association_level, class: 'form-control' %>
  </div>
        <% if @quote.blank? %>
          <%= f.hidden_field :rated_by, :value => session[:user_id] %>
        <% else %>
            <%= f.hidden_field :rated_by, :value => '0' %>
        <% end %>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-block btn-default btn-success'%>
  </div>

        </form>
      </div>
<% end %>

app/views/ideologies/edit.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
<h1 class="margin-base-vertical text-center">Editing Ideology</h1>
</div>
<%= render 'form' %>

    <p class='text-center'>
<%= link_to 'ShowAll', ideologies_path, class: 'btn btn-default btn-xs' %>
</p>
  </div>
  </div>

app/views/ideologies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default">
      <p id="notice"><%= notice %></p>

      <h1 class="margin-base-vertical text-center">Listing All Present Ideologies</h1>

      <table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Association</th>
      <th>Quote</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideologies.each do |ideology| %>
      <tr>
        <td><%= ideology.name %></td>
        <td><%= ideology.association_level %></td>
        <td><%= ideology.quote %></td>
        <td><%= link_to 'Edit', edit_ideology_path(ideology) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
    </div>
  </div>

app/views/ideologies/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default">
      <p id="notice"><%= notice %></p>

      <h1 class="margin-base-vertical text-center">Random Quote</h1>

      <table class="table table-striped table-condensed table-hover">

        <thead>
        <tr>
          <th>Author</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <td><%= @quote.author %></td>
        <td><%= @quote.content %></td>
        </tbody>
      </table>


<%= render 'form', :quote => @quote %>

      </div>
    </div>
</div>

app/views/ideologies/show.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
<h2 class="margin-base-vertical text-center" id="notice"><%= notice %></h2>
</div>
<p class='text-center'>
  <strong >Name:</strong>
  <%= @ideology.name %>
</p>

<p class='text-center'>
  <strong>Association level:</strong>
  <%= @ideology.association_level %>
</p>

<p class='text-center'>
  <strong>Quote:</strong>
  <%= @ideology.quote %>
</p>
    <p class='text-center'>
<%= link_to 'Edit', edit_ideology_path(@ideology), class: 'btn btn-default btn-xs' %>
<%= link_to 'ShowAll', ideologies_path, class: 'btn btn-default btn-xs' %>
    </p>
</div>
  </div>